apiVersion: v1
kind: Service
metadata:
  name: ibmmq-headless-server
  namespace: ibmmq
  labels:
    app: ibmmq
spec:
  ports:
  - name: ibmmq-port
    port: 1414
  - name: console-port
    port: 9443
  clusterIP: None
  selector:
    app: ibmmq
