apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ibmmq
  namespace: ibmmq
spec:
  selector:
    # 必須與 ".spec.template.metadata.labels" 相同
    matchLabels:
      app: ibmmq
  serviceName: "ibmmq"
  replicas: 1
  template:
    metadata:
      # 必須與 ".spec.selector.matchLabels" 相同
      labels:
        app: ibmmq
    spec:
      securityContext:
        fsGroup: 1001
      terminationGracePeriodSeconds: 30
      containers:
      - name: ibmmq
        image: icr.io/ibm-messaging/mq:9.2.5.0-r1
        ports:
        - containerPort: 1414
          name: ibmmq
        - containerPort: 9443
          name: console
        # 指定將 pvc 掛載到特定的目錄上
        volumeMounts:
        - name: data
          mountPath: /mnt/mqm
        env:
        - name: LICENSE
          value: accept
        - name: MQ_QMGR_NAME
          value: QM_1
        - name: MQ_ADMIN_PASSWORD
          value: passw0rd
        - name: MQ_APP_PASSWORD
          value: passw0rd
  # 使用 persistent volume 來確保資料不會因為 pod reschedule 而消失
  # 以下是使用 volumeClaimTemplates + StorageClass 來完成
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ibmmq-storage-class"
      resources:
        requests:
          storage: 5Gi