apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibmmq-pv1
  labels:
    type: local
spec:
  storageClassName: ibmmq-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/ericchen/mqdata"
