apiVersion: v1
kind: Service
metadata:
  name: ibmmq-service
  namespace: ibmmq
  labels:
    app: ibmmq
spec:
  type: NodePort
  ports:
  - name: ibmmq-port
    protocol: "TCP"
    port: 1414
    nodePort: 30000
    targetPort: 1414
  - name: console-port
    protocol: "TCP"
    port: 9443
    nodePort: 30001
    targetPort: 9443
  selector:
    app: ibmmq